/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OauthConsentRouteImport } from './routes/oauth.consent'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated.dashboard.index'
import { Route as WalletTopupSuccessRouteImport } from './routes/wallet.topup.success'
import { Route as WalletTopupCancelRouteImport } from './routes/wallet.topup.cancel'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth.google.callback'
import { Route as AuthenticatedDashboardUsageRouteImport } from './routes/_authenticated.dashboard.usage'
import { Route as AuthenticatedDashboardTransactionsRouteImport } from './routes/_authenticated.dashboard.transactions'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated.dashboard.settings'
import { Route as AuthenticatedDashboardKeysRouteImport } from './routes/_authenticated.dashboard.keys'
import { Route as AuthenticatedDashboardAppsRouteImport } from './routes/_authenticated.dashboard.apps'
import { Route as AuthenticatedDashboardAccessGroupsRouteImport } from './routes/_authenticated.dashboard.access-groups'

const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const WalletTopupSuccessRoute = WalletTopupSuccessRouteImport.update({
  id: '/wallet/topup/success',
  path: '/wallet/topup/success',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletTopupCancelRoute = WalletTopupCancelRouteImport.update({
  id: '/wallet/topup/cancel',
  path: '/wallet/topup/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/google/callback',
  path: '/google/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedDashboardUsageRoute =
  AuthenticatedDashboardUsageRouteImport.update({
    id: '/dashboard/usage',
    path: '/dashboard/usage',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardTransactionsRoute =
  AuthenticatedDashboardTransactionsRouteImport.update({
    id: '/dashboard/transactions',
    path: '/dashboard/transactions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/dashboard/settings',
    path: '/dashboard/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardKeysRoute =
  AuthenticatedDashboardKeysRouteImport.update({
    id: '/dashboard/keys',
    path: '/dashboard/keys',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardAppsRoute =
  AuthenticatedDashboardAppsRouteImport.update({
    id: '/dashboard/apps',
    path: '/dashboard/apps',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardAccessGroupsRoute =
  AuthenticatedDashboardAccessGroupsRouteImport.update({
    id: '/dashboard/access-groups',
    path: '/dashboard/access-groups',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/developers': typeof DevelopersRoute
  '/docs': typeof DocsRoute
  '/partner': typeof PartnerRoute
  '/pricing': typeof PricingRoute
  '/security': typeof SecurityRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/dashboard/access-groups': typeof AuthenticatedDashboardAccessGroupsRoute
  '/dashboard/apps': typeof AuthenticatedDashboardAppsRoute
  '/dashboard/keys': typeof AuthenticatedDashboardKeysRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/transactions': typeof AuthenticatedDashboardTransactionsRoute
  '/dashboard/usage': typeof AuthenticatedDashboardUsageRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/wallet/topup/cancel': typeof WalletTopupCancelRoute
  '/wallet/topup/success': typeof WalletTopupSuccessRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/developers': typeof DevelopersRoute
  '/docs': typeof DocsRoute
  '/partner': typeof PartnerRoute
  '/pricing': typeof PricingRoute
  '/security': typeof SecurityRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/dashboard/access-groups': typeof AuthenticatedDashboardAccessGroupsRoute
  '/dashboard/apps': typeof AuthenticatedDashboardAppsRoute
  '/dashboard/keys': typeof AuthenticatedDashboardKeysRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/transactions': typeof AuthenticatedDashboardTransactionsRoute
  '/dashboard/usage': typeof AuthenticatedDashboardUsageRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/wallet/topup/cancel': typeof WalletTopupCancelRoute
  '/wallet/topup/success': typeof WalletTopupSuccessRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/developers': typeof DevelopersRoute
  '/docs': typeof DocsRoute
  '/partner': typeof PartnerRoute
  '/pricing': typeof PricingRoute
  '/security': typeof SecurityRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/_authenticated/dashboard/access-groups': typeof AuthenticatedDashboardAccessGroupsRoute
  '/_authenticated/dashboard/apps': typeof AuthenticatedDashboardAppsRoute
  '/_authenticated/dashboard/keys': typeof AuthenticatedDashboardKeysRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/dashboard/transactions': typeof AuthenticatedDashboardTransactionsRoute
  '/_authenticated/dashboard/usage': typeof AuthenticatedDashboardUsageRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/wallet/topup/cancel': typeof WalletTopupCancelRoute
  '/wallet/topup/success': typeof WalletTopupSuccessRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/developers'
    | '/docs'
    | '/partner'
    | '/pricing'
    | '/security'
    | '/oauth/consent'
    | '/dashboard/access-groups'
    | '/dashboard/apps'
    | '/dashboard/keys'
    | '/dashboard/settings'
    | '/dashboard/transactions'
    | '/dashboard/usage'
    | '/auth/google/callback'
    | '/wallet/topup/cancel'
    | '/wallet/topup/success'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/developers'
    | '/docs'
    | '/partner'
    | '/pricing'
    | '/security'
    | '/oauth/consent'
    | '/dashboard/access-groups'
    | '/dashboard/apps'
    | '/dashboard/keys'
    | '/dashboard/settings'
    | '/dashboard/transactions'
    | '/dashboard/usage'
    | '/auth/google/callback'
    | '/wallet/topup/cancel'
    | '/wallet/topup/success'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/developers'
    | '/docs'
    | '/partner'
    | '/pricing'
    | '/security'
    | '/oauth/consent'
    | '/_authenticated/dashboard/access-groups'
    | '/_authenticated/dashboard/apps'
    | '/_authenticated/dashboard/keys'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/dashboard/transactions'
    | '/_authenticated/dashboard/usage'
    | '/auth/google/callback'
    | '/wallet/topup/cancel'
    | '/wallet/topup/success'
    | '/_authenticated/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DevelopersRoute: typeof DevelopersRoute
  DocsRoute: typeof DocsRoute
  PartnerRoute: typeof PartnerRoute
  PricingRoute: typeof PricingRoute
  SecurityRoute: typeof SecurityRoute
  OauthConsentRoute: typeof OauthConsentRoute
  WalletTopupCancelRoute: typeof WalletTopupCancelRoute
  WalletTopupSuccessRoute: typeof WalletTopupSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/wallet/topup/success': {
      id: '/wallet/topup/success'
      path: '/wallet/topup/success'
      fullPath: '/wallet/topup/success'
      preLoaderRoute: typeof WalletTopupSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/topup/cancel': {
      id: '/wallet/topup/cancel'
      path: '/wallet/topup/cancel'
      fullPath: '/wallet/topup/cancel'
      preLoaderRoute: typeof WalletTopupCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/dashboard/usage': {
      id: '/_authenticated/dashboard/usage'
      path: '/dashboard/usage'
      fullPath: '/dashboard/usage'
      preLoaderRoute: typeof AuthenticatedDashboardUsageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/transactions': {
      id: '/_authenticated/dashboard/transactions'
      path: '/dashboard/transactions'
      fullPath: '/dashboard/transactions'
      preLoaderRoute: typeof AuthenticatedDashboardTransactionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/keys': {
      id: '/_authenticated/dashboard/keys'
      path: '/dashboard/keys'
      fullPath: '/dashboard/keys'
      preLoaderRoute: typeof AuthenticatedDashboardKeysRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/apps': {
      id: '/_authenticated/dashboard/apps'
      path: '/dashboard/apps'
      fullPath: '/dashboard/apps'
      preLoaderRoute: typeof AuthenticatedDashboardAppsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/access-groups': {
      id: '/_authenticated/dashboard/access-groups'
      path: '/dashboard/access-groups'
      fullPath: '/dashboard/access-groups'
      preLoaderRoute: typeof AuthenticatedDashboardAccessGroupsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardAccessGroupsRoute: typeof AuthenticatedDashboardAccessGroupsRoute
  AuthenticatedDashboardAppsRoute: typeof AuthenticatedDashboardAppsRoute
  AuthenticatedDashboardKeysRoute: typeof AuthenticatedDashboardKeysRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardTransactionsRoute: typeof AuthenticatedDashboardTransactionsRoute
  AuthenticatedDashboardUsageRoute: typeof AuthenticatedDashboardUsageRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardAccessGroupsRoute:
    AuthenticatedDashboardAccessGroupsRoute,
  AuthenticatedDashboardAppsRoute: AuthenticatedDashboardAppsRoute,
  AuthenticatedDashboardKeysRoute: AuthenticatedDashboardKeysRoute,
  AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
  AuthenticatedDashboardTransactionsRoute:
    AuthenticatedDashboardTransactionsRoute,
  AuthenticatedDashboardUsageRoute: AuthenticatedDashboardUsageRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AuthRouteChildren {
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DevelopersRoute: DevelopersRoute,
  DocsRoute: DocsRoute,
  PartnerRoute: PartnerRoute,
  PricingRoute: PricingRoute,
  SecurityRoute: SecurityRoute,
  OauthConsentRoute: OauthConsentRoute,
  WalletTopupCancelRoute: WalletTopupCancelRoute,
  WalletTopupSuccessRoute: WalletTopupSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
